In [1]:
from tensorflow.keras.models import load_model

In [2]:
model = load_model('model.h5')

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [3]:
import pickle

In [4]:
with open ('ohe.pkl','rb') as file:
    ohe = pickle.load(file)

with open ('label_encoder_gender.pkl','rb') as file:
    label_encoder_gender = pickle.load(file)

with open ('scalar.pkl','rb') as file:
    scalar = pickle.load(file)

In [5]:
input_data = {
    'CreditScore': 600,
    'Geography' : 'France',
    'Gender' : 'Male',
    'Age' : 40,
    'Tenure' : 3,
    'Balance': 60000,
    'NumOfProducts' : 2,
    'HasCrCard' : 1,
    'IsActiveMember' : 1,
    'EstimatedSalary' : 50000
}

In [6]:
geo_encoded = ohe.transform([[input_data['Geography']]]).toarray()

d:\Arjun\Study\Simple ANN Project\.venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [7]:
import pandas as pd

In [8]:
geo_encoded_df = pd.DataFrame(geo_encoded,columns=ohe.get_feature_names_out(['Geography']))
geo_encoded_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [9]:
input_df = pd.DataFrame([input_data])

In [10]:
input_df['Gender'] = label_encoder_gender.fit_transform(input_df['Gender'])

In [11]:
input_df = pd.concat([input_df.drop('Geography',axis=1),geo_encoded_df],axis = 1)

In [12]:
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,0,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [13]:
input_scaled = scalar.fit_transform(input_df)

In [14]:
prediction = model.predict(input_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 229ms/step

In [15]:
prediction_prob = prediction[0][0]

In [16]:
if prediction_prob>0.5:
    print( "Likely to Churn")
else:
    print( "Not likely to Churn")

Not likely to Churn